# Generated by Django 5.0 on 2023-12-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('employee_no', models.IntegerField()),
                ('valuation_in_dollars', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
